framework:
    messenger:
        transports:
            sync: 'sync://'

        buses:
            command.bus: ~
            query.bus: ~
            event.bus:
                default_middleware: allow_no_handlers

        default_bus: event.bus