version: '3.8'

services:
  collectordb:
    container_name: collector-db
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=collector
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=collector
    volumes:
      - ./database:/var/lib/postgresql/data/
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U collector" ]
      interval: 2s
      timeout: 20s
      retries: 10

  collectorphp:
    container_name: collector-php-fpm
    build:
      context: .
    depends_on:
      collectordb:
        condition: service_healthy
    volumes:
      - .:/var/www

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    ports:
      - "8011:80"
    depends_on:
      - collectorphp
      - collectordb

volumes:
  database: